## prometheus.yml ##

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

#rule_files:
#  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'tasks'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['userservice:8080']
        labels:
          group: 'users'

  - job_name: 'cadvisor'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['task-cadvisor:8080']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['task-node-exporter:9100']
