version: "3"
services:
  mongo:
    image: "mongo"
    container_name: "mongo-log"
    networks:
      - microservice
    volumes:
      - task-mongo-data:/data/db
    ports:
      - "27017:27017"

  etcd:
    image: "bitnami/etcd"
    container_name: "task-etcd"
    networks:
      - microservice
    ports:
      - "12379:2379"
      - "12380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  worker-microservice:
    build:
      context: .
      dockerfile: tasks-manager-worker-service/Dockerfile
    container_name: "worker-microservice"
    networks:
      - microservice
    depends_on:
      - mongo

    volumes:
      - /Users/Al/Development/golang/src/github.com/ALiuGuanyan/distributed-tasks-scheduling/microservices/tasks-manager-worker-service/main:/app/main:ro
      - /Users/Al/Development/golang/src/github.com/ALiuGuanyan/distributed-tasks-scheduling/microservices/conf/tasks-manager-worker-config.json:/app/config:ro


  master-microservice:
    build:
      context: .
      dockerfile: tasks-manager-master-service/Dockerfile
    container_name: "master-microservice"
    ports:
      - "10010:8080"
      - "50051:50051"
    networks:
      - microservice
    depends_on:
      - mongo

    volumes:
      - /Users/Al/Development/golang/src/github.com/ALiuGuanyan/distributed-tasks-scheduling/microservices/tasks-manager-master-service/main:/app/main:ro
      - /Users/Al/Development/golang/src/github.com/ALiuGuanyan/distributed-tasks-scheduling/microservices/conf/tasks-manager-master-config.json:/app/config:ro

  cadvisor:
    image: "gcr.io/google-containers/cadvisor"
    container_name: "task-cadvisor"
    ports:
      - "9091:8080"
    networks:
      - microservice
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: "prom/prometheus"
    container_name: "task-prometheus"
    ports:
      - "9090:9090"
    networks:
      - microservice
    volumes:
      - /Users/Al/Development/golang/src/github.com/ALiuGuanyan/distributed-tasks-scheduling/microservices/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
      - grafana

  node-exporter:
    image: "prom/node-exporter"
    container_name: "task-node-exporter"
    ports:
      - "9092:9100"
    networks:
      - microservice

  grafana:
    image: "grafana/grafana"
    container_name: "task-grafana"
    ports:
      - "9093:3000"
    networks:
      - microservice
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=PACKT
      - GF_USERS_ALLOW_SIGN_UP=false

  grpcui:
    image: "wongnai/grpcui"
    environment:
      - GRPCUI_SERVER=master-microservice:50051
    ports:
      - "10012:8080"
    networks:
      - microservice
    depends_on:
      - master-microservice

networks:
  microservice:
    external: true

volumes:
  task-mongo-data:
    external: false

